# Generated by Django 6.0.2 on 2026-03-02 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_action', models.CharField(max_length=20)),
                ('table_concernee', models.CharField(max_length=50)),
                ('id_enregistrement', models.IntegerField()),
                ('ancien_donnees', models.TextField(blank=True, null=True)),
                ('nouvel_donnees', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journal',
                'ordering': ['-date_heure'],
            },
        ),
    ]
