# Generated by Django 6.0.2 on 2026-03-02 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(default=django.utils.timezone.now)),
                ('fichier', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=20)),
                ('lignes_total', models.IntegerField(blank=True, null=True)),
                ('lignes_ajoutees', models.IntegerField(blank=True, null=True)),
                ('lignes_doublons', models.IntegerField(blank=True, null=True)),
                ('lignes_erreurs', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import_log',
                'ordering': ['-date_heure'],
            },
        ),
    ]
