# Generated by Django 6.0.2 on 2026-03-02 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'classe',
                'ordering': ['numero', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cours',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=10, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('role', models.CharField(blank=True, default='Formateur', max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classe_affectee', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tuteur',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=10, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('presence', models.CharField(blank=True, max_length=2, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='academics.classe')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='academics.cours')),
                ('tuteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='academics.tuteur')),
            ],
            options={
                'db_table': 'etudiant',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='academics.classe')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences_dates', to='academics.cours')),
            ],
            options={
                'db_table': 'presence',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PresenceEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(max_length=2)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='academics.etudiant')),
            ],
            options={
                'db_table': 'presence_etudiant',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TuteurPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(max_length=2)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='academics.tuteur')),
            ],
            options={
                'db_table': 'tuteur_presence',
                'ordering': ['date'],
            },
        ),
    ]
